// generated by ChatGPT

const isHex = (str) => /^[0-9a-fA-F]+$/.test(str.trim());

// Get all span elements
const spans = Array.from(dom.querySelectorAll("span, p"));

// Group spans by className
const classMap = new Map();

spans.forEach(span => {
    const className = span.className.trim();
    if (!className) return; // skip spans with no class

    if (!classMap.has(className)) {
        classMap.set(className, { elements: [], hexCount: 0 });
    }

    const entry = classMap.get(className);
    entry.elements.push(span);

    if (isHex(span.textContent)) {
        entry.hexCount++;
    }
});

// Find classes where > 50% of spans contain hex
const garbageClasses = [];
for (const [className, data] of classMap.entries()) {
    const ratio = data.hexCount / data.elements.length;
    if (ratio > 0.5) {
        garbageClasses.push(className);
    }
}

// Remove all spans with "garbage" classes
garbageClasses.forEach(className => {
    const elements = classMap.get(className).elements;
    elements.forEach(el => console.log(el));
    elements.forEach(el => el.remove());
});

return 0 < garbageClasses.length;